// angular-examples/m004-router/src/app/create-user/create-user.component.ts
import { Component, OnInit } from "@angular/core";
import { HttpClient, HttpHeaders } from "@angular/common/http";
import { Router } from "@angular/router";
import { environment } from "../../environments/environment";
import { User } from "./user";

const httpOptions = {
  headers: new HttpHeaders({ "Content-Type": "application/json" })
};

interface UserType {
  id: number;
  name: string;
  genderCode: string;
}

@Component({
  selector: "app-create-user",
  templateUrl: "./create-user.component.html",
  styleUrls: ["./create-user.component.css"]
})
export class CreateUserComponent implements OnInit {
  model = new User("", 1);

  constructor(private router: Router, private http: HttpClient) {}

  ngOnInit() {}

  onCreate() {
    this.http
      .post<UserType>(
        `${environment.host}/users`,
        {
          name: this.model.name,
          genderCode: String(this.model.genderCode)
        },
        httpOptions
      )
      .subscribe(data => {
        this.model = new User("", 1);
        this.router.navigate(["/user/", data.id]);
      });
  }
}

<div>
  <h4>form</h4>
  名前:
  <input name="name" placeholder="name" [(ngModel)]="model.name" />
  <br />
  <br />
  性別:
  <input type="radio" id="male" name="genderCode" [value]="1" [(ngModel)]="model.genderCode" [checked]="model.genderCode === 1" />
  <label for="male" style="padding-right:8px">男性</label>
  <input type="radio" id="female" name="genderCode" [value]="2" [(ngModel)]="model.genderCode" [checked]="model.genderCode === 2" />
  <label for="female">女性</label>
  <br />
  <br />
  <button (click)="onCreate()">登録</button>
  <br />
</div>

// nuxtjs-exapmles/004-router/pages/createUser/index.vue
<template>
  <section class="container">
    <div>
      <Header/>
      <h1>form</h1>
      <br />
          名前:
      <input v-model="input.name" placeholder="name"/>
      <br />
      <br />
      性別:
      <input type="radio" id="male" value="1" v-model="input.genderCode" />
      <label for="male" style="padding-right:8px">男性</label>
      <input type="radio" id="female" value="2" v-model="input.genderCode" />
      <label for="female">女性</label>
      <br />
      <br />
      <button v-on:click="save">登録</button>
    </div>
  </section>
</template>

<script>
import axios from "axios";
import Header from "~/components/Header.vue";
import { log } from "util";

const host = process.env.host || "http://localhost:3000";

export default {
  components: {
    Header
  },
  data() {
    return {
      input: {
        name: "",
        genderCode: "1"
      }
    };
  },
  methods: {
    save: async function() {
      const response = await fetch(`${host}/users`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(this.input)
      });

      if (!response.ok) {
        return alert("通信エラー");
      }

      const result = await response.json();

      this.$router.push("users/" + result.id);
    }
  }
};
</script>

<style>
.container {
  min-height: 100vh;
  padding: 2rem;
}
</style>
