// angular-examples/m004-router/src/app/users/users.component.ts
import { Component, OnInit } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { environment } from "../../environments/environment";

interface UserType {
  id: number;
  name: string;
  genderCode: string;
}

@Component({
  selector: "app-users",
  templateUrl: "./users.component.html",
  styleUrls: ["./users.component.css"]
})
export class UsersComponent implements OnInit {
  users: UserType[];

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.getUsers();
  }

  getUsers() {
    this.http.get<UserType[]>(`${environment.host}/users`).subscribe(data => {
      this.users = data;
    });
  }

  onDelete(id: number) {
    this.http
      .delete<UserType>(`${environment.host}/users/${id}`)
      .subscribe(_ => {
        this.getUsers();
      });
  }
}

<div>
  <h4>users</h4>
  <table border="1" style="width:30rem">
    <tr>
      <th>id</th>
      <th>名前</th>
      <th>性別</th>
      <th>action</th>
    </tr>
    <tr *ngFor="let user of users">
      <td>
        <a routerLink="/user/{{user.id}}">{{user.id}} </a> </td>
      <td>
        {{user.name}}
      </td>
      <td>
        {{user.genderCode === "1" ? "男性" : "女性" }}
      </td>
      <td>
        <button (click)="onDelete(user.id)">削除</button>
      </td>
    </tr>
  </table>
</div>

// vue-examples/004-router/src/views/Users.vue
<template>
  <div>
    <h4>users</h4>
    <table border="1" style="width:30rem">
      <tr>
        <th>id</th>
        <th>名前</th>
        <th>性別</th>
        <th>action</th>
      </tr>
      <tr v-for="item in items" :key="item.id">
        <td><router-link v-bind:to="{ name: 'user', params: { id: item.id }}">{{item.id}}</router-link></td>
        <td>{{item.name}}</td>
        <td>{{item.genderCode == "1" ? "男性" : "女性"}}</td>
        <td>
          <button v-on:click="remove(item.id)">削除</button>
        </td>
      </tr>
    </table>
  </div>
</template>

<script>
const host = process.env.VUE_APP_HOST || "http://localhost:3000";

export default {
  name: "Users",
  data() {
    return {
      items: []
    };
  },
  created: function() {
    this.getItems();
  },
  methods: {
    getItems: async function() {
      const response = await fetch(`${host}/users`);

      if (!response.ok) {
        return alert("通信エラー");
      }

      const result = await response.json();
      this.items = result;
    },
    remove: async function(id) {
      const response = await fetch(`${host}/users/${id}`, {
        method: "DELETE",
        headers: {
          "Content-Type": "application/json"
        }
      });

      if (!response.ok) {
        return alert("削除に失敗しました");
      }
      // リストを再取得
      this.getItems();
    }
  }
};
</script>
