// angular-examples/m004-router/src/app/user/user.component.ts
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
import { HttpClient } from "@angular/common/http";
import { environment } from "../../environments/environment";

interface UserType {
  id: number;
  name: string;
  genderCode: string;
}

@Component({
  selector: "app-user",
  templateUrl: "./user.component.html",
  styleUrls: ["./user.component.css"]
})
export class UserComponent implements OnInit {
  user: UserType = {
    id: 0,
    name: "",
    genderCode: "1"
  };

  constructor(private route: ActivatedRoute, private http: HttpClient) {}

  ngOnInit() {
    const id = this.route.snapshot.paramMap.get("id");

    this.http
      .get<UserType>(`${environment.host}/users/${id}`)
      .subscribe(data => {
        this.user = data;
      });
  }
}

<div>
  <h4>users</h4>
  <table border="1" style="width:30rem">
    <tr>
      <th>id</th>
      <th>名前</th>
      <th>性別</th>
    </tr>
    <tr>
      <td>
        {{user.id}}
      </td>
      <td>
        {{user.name}}
      </td>
      <td>
        {{user.genderCode === "1" ? "男性" : "女性" }}
      </td>
    </tr>
  </table>
</div>

// vue-examples/004-router/src/views/User.vue
<template>
  <div>
    <h4>user</h4>
    <table border="1" style="width:30rem">
      <tr>
        <th>id</th>
        <th>名前</th>
        <th>性別</th>
      </tr>
      <tr>
        <td>{{item.id}}</td>
        <td>{{item.name}}</td>
        <td>{{item.genderCode == "1" ? "男性" : "女性"}}</td>
      </tr>
    </table>
  </div>
</template>

<script>
const host = process.env.VUE_APP_HOST || "http://localhost:3000";

export default {
  name: "User",
  data() {
    return {
      item: {
        id: 0,
        name: "",
        genderCode: "1"
      }
    };
  },
  created: function() {
    this.getItem();
  },
  methods: {
    getItem: async function() {
      const response = await fetch(`${host}/users/${this.$route.params.id}`);

      if (!response.ok) {
        return alert("通信エラー");
      }

      const result = await response.json();
      this.item = result;
    }
  }
};
</script>
